services:
  ejs-api:
    # Uncomment to build locally
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/bongodevs/yt-cipher:master
    container_name: ejs_signature_api
    ports:
      - "8001:8001"
    # environment: # UNCOMMENT THIS LINE AND API_TOKEN TO ADD A PASSWORD
    #   - API_TOKEN=test
    restart: unless-stopped
